# Generated by Django 3.2.7 on 2022-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('attraction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('areacode', models.IntegerField(null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('image2', models.CharField(blank=True, max_length=255, null=True)),
                ('mapx', models.FloatField(blank=True, null=True)),
                ('mapy', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('readcount', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'attraction',
            },
        ),
    ]
