# Generated by Django 4.1.1 on 2022-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeobo', '0001_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
