# Generated by Django 3.2.7 on 2022-10-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeobo', '0002_user_rename_areacode_attraction_area_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction_2',
            fields=[
                ('attraction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('cnt', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'attraction_2',
            },
        ),
    ]
